Repository sardapv/angular-material-starter-template, pull requests merged in 2021-07, with the labels that each got.

#14 Bugfixes
  cypress/integration/spec.ts
  package-lock.json
Labels: bug

#20 Route progressbar
  README.md
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/main.ts
Labels: enhancement

#21 environment corrections
  src/environments/environment.prod.ts
  src/main.ts
Labels: bug

#15 Prettier
  .prettierignore
  .prettierrc
  package-lock.json
  package.json
Labels: enhancement

#23 prettier enhancements
  .eslintrc.json
  .github/workflows/build-deploy.yml
  README.md
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/features/after-login/after-login-routing.module.ts
  src/app/features/before-login/before-login-routing.module.ts
  src/app/features/before-login/before-login.component.spec.ts
  src/app/shared/components/scam/scam.module.ts
Labels: enhancement

#17 npx utility added
  README.md
  angular.json
  bin/generate-app.js
  logoForThisRepo.png
  package-lock.json
  package.json
  src/app/app.component.ts
  src/styles/shared/_global.scss
Labels: documentation, enhancement

#27 pre-commit hooks
  .husky/pre-commit
  README.md
  bin/generate-app.js
  logoForThisRepo.png
  package-lock.json
  package.json
  src/app/app.component.html
Labels: documentation, enhancement

#29 added code coverage workflow, fixes #6
  .github/workflows/coverage.yml
  README.md
  jest.config.js
  package-lock.json
  package.json
Labels: enhancement

#30 Add lighthouse dev dependency
  .gitignore
  README.md
  bin/generate-app.js
  lighthouse.js
  logoForThisRepo.png
  package-lock.json
  package.json
Labels: enhancement

#35 Switch to using Cypress code coverage
  .github/workflows/coverage.yml
  .gitignore
  .prettierignore
  .prettierrc
  angular.json
  cypress/coverage.webpack.js
  cypress/plugins/index.js
  cypress/support/index.ts
  jest.config.js
  package-lock.json
  package.json
  src/app/core/services/auth.service.spec.ts
  src/app/features/after-login/after-login.component.spec.ts
Labels: documentation, enhancement
